# Generated by Django 3.2.7 on 2021-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210914_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
