# Generated by Django 3.2.7 on 2021-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale',
            field=models.FloatField(),
        ),
    ]
