# Generated by Django 3.2.7 on 2021-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210914_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_sale',
            field=models.FloatField(null=True),
        ),
    ]
