# Generated by Django 3.2.7 on 2021-09-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_sale_total_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sale',
        ),
    ]
