# Generated by Django 3.2.7 on 2021-09-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_rename_employee_sale_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='employee_name',
            new_name='employee',
        ),
    ]
