# Generated by Django 3.2.7 on 2021-09-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_alter_addbonus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbonus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
